management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
    preferIpAddress: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9190/eureka
    register-with-eureka: true
server:
  port: 9998
spring:
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: http://localhost:9190/admin        
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: crud
          uri: lb://CRUD-COMPROBANTE
          predicates:
            - Path=/crud-comprobante/**
logging:
  file:
    name: api-gateway.log
info:
  author: Byon Santiago Segovia Quintero
  description: 'API-GATEWAY Microservicio ejemplo cooperatvias'
  version: '2.0'
  name: Api - Gateway